apiVersion: v1
kind: Service
metadata:
  name: sipback-lb
  namespace: dpetrocelli
spec:
  type: ClusterIP
  selector:
    app: sipback
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080