apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webserver-deployment
  namespace: dpetrocelli
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 1 
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: dpetrocelli/webserver_prueba:latest
        ports:
        - containerPort: 8080
