apiVersion: v1
kind: Service
metadata:
  name: postgre-lb
  namespace: dpetrocelli
spec:
  type: ClusterIP
  selector:
    app: postgre
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432