apiVersion: v1
kind: Service
metadata:
  name: webserver-lb
  namespace: dpetrocelli
spec:
  type: LoadBalancer
  selector:
    app: webserver
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
