# File: .github/workflows/workflow.yml
# Okteto documentation: https://www.okteto.com/docs/cloud/github-actions/
# 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: cicd_pipeline

jobs:

  # build_front:
  #   name: Build FrontEnd and publish to Docker Registry
  #   runs-on: ubuntu-latest

  #   steps:

  #     # [STEP 1] - Checkout Code
  #     - name: Checkout code from repo
  #       uses: actions/checkout@v2
      
  #     # [STEP 2] - Check filesystem structure and get it the correct path
  #     - name: Check filesystem structure
  #       run: ls -la
        

  #     # [STEP 2] - Build & Store Docker image
  #     - name: Login to Docker Hub
  #       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
  #     - name: Build Frontend Container image
  #       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FRONT_REPO }}:latest ./frontend-client
        
  #     - name: Publish Docker image
  #       run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FRONT_REPO }}:latest


  #     - uses: actions-hub/kubectl@master
  #       env:
  #         KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
  #       with:
  #         args: apply -f k8s/okteto_k8s_github_actions/yamls/deployment.yaml
  
  # build_back:
  #   name: Build Backend and publish to Docker Registry
  #   runs-on: ubuntu-latest

  #   steps:

  #     # [STEP 1] - Checkout Code
  #     - name: Checkout code from repo
  #       uses: actions/checkout@v2
      
  #     # [STEP 2] - Set UP JDK 11 
  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: '11'
  #         distribution: 'temurin'
  #         cache: maven
      
  #     # [STEP 3] - Build JAR with MVN 
  #     - name: Build package with Maven
  #       run: mvn -B clean package -DskipTests --file backend-api/pom.xml
        
  #     # [STEP 4] - Build & Store Docker image
  #     - name: Login to Docker Hub
  #       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
  #     - name: Build Backend Container image
  #       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.BACK_REPO }}:latest ./backend-api
        
  #     - name: Publish Docker image
  #       run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.BACK_REPO }}:latest


   
  # deploy_front_to_k8s:
  #   needs: [build_front]
  #   name: Deploy frontend to k8s
  #   runs-on: ubuntu-latest

  #   steps:

  #     # [STEP 1] - Checkout Code
  #     - name: Checkout code from repo
  #       uses: actions/checkout@v2

  #     # [STEP 2] - Deploy Pods
  #     - name: Deploy Pods (containers)
  #       uses: actions-hub/kubectl@master
  #       env:
  #         KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
  #       with:
  #         args: apply -f k8s/okteto_k8s/yamls/front/01-deployment.yaml 

  #     # [STEP 3] - Deploy Service (Load Balancer)
  #     - name: Deploy services (LB)
  #       uses: actions-hub/kubectl@master
  #       env:
  #         KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
  #       with:
  #         args: apply -f k8s/okteto_k8s/yamls/front/02-service.yaml


  deploy_back_to_k8s:
    # needs: [build_back]
    name: Deploy backend to k8s
    runs-on: ubuntu-latest

    steps:

      # [STEP 1] - Checkout Code
      - name: Checkout code from repo
        uses: actions/checkout@v2

      # [STEP 2] - Deploy Pods
      - name: Deploy Pods (containers)
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f k8s/okteto_k8s/yamls/back/01-deployment.yaml 

      # [STEP 3] - Deploy Service (Load Balancer)
      - name: Deploy services (LB)
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f k8s/okteto_k8s/yamls/back/02-service.yaml